package com.log660.beans;



import java.util.HashSet;
import java.util.Set;

/**
 * Adresse generated by hbm2java
 */
public class Adresse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int guid;
	private int nocivique;
	private String rue;
	private String ville;
	private String province;
	private String codepostal;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Adresse() {
	}

	public Adresse(int nocivique, String rue, String ville, String province, String codepostal, Set<Utilisateur> utilisateurs) {
		this.nocivique = nocivique;
		this.rue = rue;
		this.ville = ville;
		this.province = province;
		this.codepostal = codepostal;
		this.utilisateurs = utilisateurs;
	}

	public int getGuid() {
		return this.guid;
	}
	
	public void setGuid(int guid) {
		this.guid = guid;
	}

	public int getNocivique() {
		return this.nocivique;
	}

	public void setNocivique(int nocivique) {
		this.nocivique = nocivique;
	}

	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCodepostal() {
		return this.codepostal;
	}

	public void setCodepostal(String codepostal) {
		this.codepostal = codepostal;
	}
	
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}
}
