package com.log660.beans;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cartecredit generated by hbm2java
 */
public class Cartecredit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int guid;
	private String marque;
	private long nocarte;
	private Date dateexpiration;
	private Short cvv;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Cartecredit() {
	}

	public Cartecredit(String marque, long nocarte, Date dateexpiration, Short cvv, Set<Utilisateur> utilisateurs) {
		this.marque = marque;
		this.nocarte = nocarte;
		this.dateexpiration = dateexpiration;
		this.cvv = cvv;
		this.utilisateurs = utilisateurs;
	}

	public int getGuid() {
		return this.guid;
	}
	
	public void setGuid(int guid) {
		this.guid = guid;
	}

	public String getMarque() {
		return this.marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	public long getNocarte() {
		return this.nocarte;
	}

	public void setNocarte(long nocarte) {
		this.nocarte = nocarte;
	}

	public Date getDateexpiration() {
		return this.dateexpiration;
	}

	public void setDateexpiration(Date dateexpiration) {
		this.dateexpiration = dateexpiration;
	}

	public Short getCvv() {
		return this.cvv;
	}

	public void setCvv(Short cvv) {
		this.cvv = cvv;
	}

	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
