package com.log660.beans;



import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int guid;
	private String titre;
	private Short anneesortie;
	private String paysproduction;
	private String langueoriginale;
	private Short dureefilm;
	private Clob resumescenario;
	private Short quantite;
	private Set<Genre> genres = new HashSet<Genre>(0);
	private Set<Personnel> personnels = new HashSet<Personnel>(0);
	private Set<Locationfilm> locationfilms = new HashSet<Locationfilm>(0);

	public Film() {
	}

	public Film(String titre, Short anneesortie, String paysproduction, String langueoriginale,
			Short dureefilm, Clob resumescenario, Short quantite, Set<Genre> genres, Set<Personnel> personnels, Set<Locationfilm> locationfilms) {
		this.titre = titre;
		this.anneesortie = anneesortie;
		this.paysproduction = paysproduction;
		this.langueoriginale = langueoriginale;
		this.dureefilm = dureefilm;
		this.resumescenario = resumescenario;
		this.quantite = quantite;
		this.genres = genres;
		this.personnels = personnels;
		this.locationfilms = locationfilms;
	}

	public int getGuid() {
		return this.guid;
	}
	
	@SuppressWarnings("unused")
	private void setGuid(int guid) {
		this.guid = guid;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public Short getAnneesortie() {
		return this.anneesortie;
	}

	public void setAnneesortie(Short anneesortie) {
		this.anneesortie = anneesortie;
	}

	public String getPaysproduction() {
		return this.paysproduction;
	}

	public void setPaysproduction(String paysproduction) {
		this.paysproduction = paysproduction;
	}

	public String getLangueoriginale() {
		return this.langueoriginale;
	}

	public void setLangueoriginale(String langueoriginale) {
		this.langueoriginale = langueoriginale;
	}

	public Short getDureefilm() {
		return this.dureefilm;
	}

	public void setDureefilm(Short dureefilm) {
		this.dureefilm = dureefilm;
	}

	public Clob getResumescenario() {
		return this.resumescenario;
	}

	public void setResumescenario(Clob resumescenario) {
		this.resumescenario = resumescenario;
	}

	public Short getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Short quantite) {
		this.quantite = quantite;
	}

	public Set<Genre> getGenres() {
		return this.genres;
	}

	public void setGenres(Set<Genre> genres) {
		this.genres = genres;
	}

	public Set<Personnel> getPersonnels() {
		return this.personnels;
	}

	public void setPersonnels(Set<Personnel> personnels) {
		this.personnels = personnels;
	}

	public Set<Locationfilm> getLocationfilms() {
		return this.locationfilms;
	}

	public void setLocationfilms(Set<Locationfilm> locationfilms) {
		this.locationfilms = locationfilms;
	}

}
