package com.log660.beans;

import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int guid;
	private String nomforfait;
	private Short cout;
	private Byte quantitelocationmax;
	private Byte dureelocationmax;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Forfait() {
	}

	public Forfait(String nomforfait, Short cout, Byte quantitelocationmax, Byte dureelocationmax,
			Set<Utilisateur> utilisateurs) {
		this.nomforfait = nomforfait;
		this.cout = cout;
		this.quantitelocationmax = quantitelocationmax;
		this.dureelocationmax = dureelocationmax;
		this.utilisateurs = utilisateurs;
	}

	public int getGuid() {
		return this.guid;
	}
	
	public void setGuid(int guid) {
		this.guid = guid;
	}

	public String getNomforfait() {
		return this.nomforfait;
	}

	public void setNomforfait(String nomforfait) {
		this.nomforfait = nomforfait;
	}

	public Short getCout() {
		return this.cout;
	}

	public void setCout(Short cout) {
		this.cout = cout;
	}

	public Byte getQuantitelocationmax() {
		return this.quantitelocationmax;
	}

	public void setQuantitelocationmax(Byte quantitelocationmax) {
		this.quantitelocationmax = quantitelocationmax;
	}

	public Byte getDureelocationmax() {
		return this.dureelocationmax;
	}

	public void setDureelocationmax(Byte dureelocationmax) {
		this.dureelocationmax = dureelocationmax;
	}

	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
