package com.log660.beans;


/**
 * LocationfilmId generated by hbm2java
 */
public class LocationfilmId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nofilm;
	private int noutilisateur;

	public LocationfilmId() {
	}

	public LocationfilmId(int nofilm, int noutilisateur) {
		this.nofilm = nofilm;
		this.noutilisateur = noutilisateur;
	}

	public int getNofilm() {
		return this.nofilm;
	}

	public void setNofilm(int nofilm) {
		this.nofilm = nofilm;
	}

	public int getNoutilisateur() {
		return this.noutilisateur;
	}

	public void setNoutilisateur(int noutilisateur) {
		this.noutilisateur = noutilisateur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocationfilmId))
			return false;
		LocationfilmId castOther = (LocationfilmId) other;

		return (this.getNofilm() == castOther.getNofilm()) && (this.getNoutilisateur() == castOther.getNoutilisateur());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNofilm();
		result = 37 * result + this.getNoutilisateur();
		return result;
	}

}
