package com.log660.beans;

import java.util.Date;

/**
 * Locationfilm generated by hbm2java
 */
public class Locationfilm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LocationfilmId id;
	private Film film;
	private Utilisateur utilisateur;
	private Date dateLocationFilm;
	private Date dateRetour;

	public Locationfilm() {
	}

	public Locationfilm(Film film, Utilisateur utilisateur, Date dateLocationFilm, Date dateRetour) {
		this.film = film;
		this.utilisateur = utilisateur;
		this.dateLocationFilm = dateLocationFilm;
		this.dateRetour = dateRetour;
	}

	public LocationfilmId getId() {
		return this.id;
	}
	
	@SuppressWarnings("unused")
	private void setId(LocationfilmId id) {
		this.id = id;
	}
	
	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Date getDatelocationfilm() {
		return this.dateLocationFilm;
	}

	public void setDatelocationfilm(Date datelocationfilm) {
		this.dateLocationFilm = datelocationfilm;
	}

	public Date getDateretour() {
		return this.dateRetour;
	}

	public void setDateretour(Date dateretour) {
		this.dateRetour = dateretour;
	}

}
