package com.log660.beans;


/**
 * PersonnelId generated by hbm2java
 */
public class PersonnelId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nofilm;
	private int nopersonne;
	private int norole;
	private int id;

	public PersonnelId() {
	}

	public PersonnelId(int nofilm, int nopersonne, int norole) {
		this.nofilm = nofilm;
		this.nopersonne = nopersonne;
		this.norole = norole;
	}

	public int getNofilm() {
		return this.nofilm;
	}

	public void setNofilm(int nofilm) {
		this.nofilm = nofilm;
	}

	public int getNopersonne() {
		return this.nopersonne;
	}

	public void setNopersonne(int nopersonne) {
		this.nopersonne = nopersonne;
	}

	public int getNorole() {
		return this.norole;
	}

	public void setNorole(int norole) {
		this.norole = norole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonnelId))
			return false;
		PersonnelId castOther = (PersonnelId) other;

		return (this.getNofilm() == castOther.getNofilm()) && (this.getNopersonne() == castOther.getNopersonne())
				&& (this.getNorole() == castOther.getNorole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNofilm();
		result = 37 * result + this.getNopersonne();
		result = 37 * result + this.getNorole();
		return result;
	}

	public int getId() {
		return id;
	}

	@SuppressWarnings("unused")
	private void setId(int id) {
		this.id = id;
	}

}
