package com.log660.beans;

/**
 * Personnel generated by hbm2java
 */
public class Personnel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PersonnelId id;
	private Personne personne;
	private Rolepersonne rolePersonne;
	private Film film;

	public Personnel() {
	}

	public Personnel(Personne personne, Rolepersonne rolePersonne, Film film) {
		this.personne = personne;
		this.rolePersonne = rolePersonne;
		this.film = film;
	}

	public PersonnelId getId() {
		return this.id;
	}
	
	@SuppressWarnings("unused")
	private void setId(PersonnelId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Rolepersonne getRolepersonne() {
		return this.rolePersonne;
	}

	public void setRolepersonne(Rolepersonne rolePersonne) {
		this.rolePersonne = rolePersonne;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

}
