package com.log660.beans;



import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Personne implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int guid;
	private String nom;
	private Date datenaissance;
	private String lieunaissance;
	private String photo;
	private Clob biographie;
	private Set<Personnel> personnels = new HashSet<Personnel>(0);

	public Personne() {
	}

	public Personne(String nom, Date datenaissance, String lieunaissance, String photo, Clob biographie,
			Set<Personnel> personnels) {
		this.nom = nom;
		this.datenaissance = datenaissance;
		this.lieunaissance = lieunaissance;
		this.photo = photo;
		this.biographie = biographie;
		this.personnels = personnels;
	}

	public int getGuid() {
		return this.guid;
	}
	
	public void setGuid(int guid) {
		this.guid = guid;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	public String getLieunaissance() {
		return this.lieunaissance;
	}

	public void setLieunaissance(String lieunaissance) {
		this.lieunaissance = lieunaissance;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Clob getBiographie() {
		return this.biographie;
	}

	public void setBiographie(Clob biographie) {
		this.biographie = biographie;
	}

	public Set<Personnel> getPersonnels() {
		return this.personnels;
	}

	public void setPersonnels(Set<Personnel> personnels) {
		this.personnels = personnels;
	}

}
