package com.log660.beans;
import java.util.HashSet;
import java.util.Set;

/**
 * Rolepersonne generated by hbm2java
 */
public class Rolepersonne implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int guid;
	private String nom;
	private Set<Personnel> personnels = new HashSet<Personnel>(0);

	public Rolepersonne() {
	}

	public Rolepersonne(String nom) {
		this.nom = nom;
	}

	@SuppressWarnings("unused")
	private int getGuid() {
		return this.guid;
	}
	
	public void setGuid(int guid) {
		this.guid = guid;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	
	public Set<Personnel> getPersonnels() {
		return this.personnels;
	}

	public void setPersonnels(Set<Personnel> personnels) {
		this.personnels = personnels;
	}
}
