package com.log660.beans;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int guid;
	private Adresse adresse;
	private Cartecredit cartecredit;
	private Forfait forfait;
	private String prenom;
	private String nom;
	private String courriel;
	private long telephone;
	private Date datenaissance;
	private String motdepasse;
	private Integer matricule;
	private Set<Locationfilm> locationfilms = new HashSet<Locationfilm>(0);

	public Utilisateur() {
	}

	public Utilisateur(Adresse adresse, Cartecredit cartecredit, Forfait forfait, String prenom, String nom,
			String courriel, long telephone, Date datenaissance, String motdepasse, Integer matricule,
			Set<Locationfilm> locationfilms) {

		this.adresse = adresse;
		this.cartecredit = cartecredit;
		this.forfait = forfait;
		this.prenom = prenom;
		this.nom = nom;
		this.courriel = courriel;
		this.telephone = telephone;
		this.datenaissance = datenaissance;
		this.motdepasse = motdepasse;
		this.matricule = matricule;
		this.locationfilms = locationfilms;
	}

	public int getGuid() {
		return this.guid;
	}
	
	public void setGuid(int guid) {
		this.guid = guid;
	}

	public Adresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Adresse adresse) {
		this.adresse = adresse;
	}

	public Cartecredit getCartecredit() {
		return this.cartecredit;
	}

	public void setCartecredit(Cartecredit cartecredit) {
		this.cartecredit = cartecredit;
	}

	public Forfait getForfait() {
		return this.forfait;
	}

	public void setForfait(Forfait forfait) {
		this.forfait = forfait;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(long telephone) {
		this.telephone = telephone;
	}

	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public Integer getMatricule() {
		return this.matricule;
	}

	public void setMatricule(Integer matricule) {
		this.matricule = matricule;
	}

	public Set<Locationfilm> getLocationfilms() {
		return this.locationfilms;
	}

	public void setLocationfilms(Set<Locationfilm> locationfilms) {
		this.locationfilms = locationfilms;
	}

}
